# Generated by Django 3.0.14 on 2021-08-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null='Defualt Subject', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Subject'),
            preserve_default='Defualt Subject',
        ),
    ]
